import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import Head from "next/head";
import { Metadata } from "next";
import Provider from "./components/Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="ko">
      <Head>
        <meta name="google-adsense-account" content="ca-pub-8907240576603717" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none`}
      >
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>

  );
}
